name: Build and Deploy satama-appro.fi to Netlify

on:
  repository_dispatch:
    types:
      - build-and-deploy-satama-appro
  push:
    branches:
      - 'main'
    paths:
      - 'satama-approt/**'

env:
  SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
  SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn --immutable
      - run: yarn workspace satama-approt build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - name: Publish
        uses: Dumppiry/netlify-actions/cli@master
        with:
          args: deploy --dir=packages/satama-approt/dist --filter packages/satama-approt --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SATAMA_APPRO_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_SATAMA_APPRO_AUTH_TOKEN }}
